apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: testwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testwebapp
  template:
    metadata:
      labels:
        app: testwebapp 
    spec:
      containers:
      - name: testwebapp
        image: myid6412/testwebapp:latest
        ports:
        - containerPort: 3000
